# Generated by Django 3.1.4 on 2020-12-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectStar',
            fields=[
                ('StarID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=300)),
                ('StarAmount', models.IntegerField(default=0)),
                ('YellowCard', models.IntegerField(default=0)),
                ('Status', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffID', models.CharField(max_length=9, unique=True)),
                ('Nickname', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=20)),
                ('DepartmentName', models.CharField(max_length=40)),
                ('DepartmentCode', models.CharField(max_length=30)),
                ('WorkAge', models.IntegerField(default=0)),
                ('Status', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now=True)),
                ('StaffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StaffIDs', to='boards.staffprofile')),
                ('StarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StarIDs', to='boards.collectstar')),
            ],
        ),
    ]
